---
apiVersion: v1
kind: Namespace
metadata:
  name: ocp-lab1
  labels:
    training: "true"
    student: "labuser1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: labuser1-admin
  namespace: ocp-lab1
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: labuser1
---
apiVersion: v1
kind: Namespace
metadata:
  name: ocp-lab2
  labels:
    training: "true"
    student: "labuser2"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: labuser2-admin
  namespace: ocp-lab2
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: labuser2
---
apiVersion: v1
kind: Namespace
metadata:
  name: ocp-lab3
  labels:
    training: "true"
    student: "labuser3"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: labuser3-admin
  namespace: ocp-lab3
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: User
  name: labuser3
